language: ruby

sudo: false

rvm:
  - "2.3.0"

script: bundle exec rake spec

cache: bundler

env:
  - COVERAGE=true

addons:
  code_climate:
    repo_token: 423daed64ecdf569121bd4b69d02dac79b01f9bb2b7270eb8498f77d744ecc19
